name: 'Test commit message style and content.'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      contents: read

    steps:
      - name: Check Conventional Commit
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '(?:build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(?:\(\w+\))?:\s[a-z]{1,2}.+'
          error: "The commit message must follow the conventional commit messages guidelines"
          excludeDescription: 'true'
          excludeTitle: 'true'
          checkAllCommitMessages: 'true'
          accessToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Check Line Length
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '^[^#].{72}'
          error: 'The maximum line length of 72 characters is exceeded.'
          excludeDescription: 'true'
          excludeTitle: 'true'
          checkAllCommitMessages: 'true'
          accessToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Check for Resolves / Fixes
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '^.+(Resolves|Fixes): \#[0-9]+$'
          error: 'You need at least one "Resolves|Fixes: #<issue number>" line.'