name: "Test commit message style and content."
on: # rebuild any PRs and main branch changes
  pull_request:
    types:
        - opened
        - edited
        - reopened
        - synchronize
  push:
    branches:
      - main

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install gitlint
        run: pip install gitlint==0.19.1
      - name: Run gitlint
        run: |
          gitlint --contrib contrib-title-conventional-commits \
            --ignore=ignore-merge-commits
