name: 'Test and run format and lint checks.'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and run Dev Container task
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/sequinsbio/sequintools-devcontainer
          cacheFrom: ghcr.io/sequinsbio/sequintools-devcontainer
          push: always
          eventFilterForPush: push
          env:
            CARGO_TERM_COLOR: always
          runCmd: |
            cargo test --all-features
            cargo fmt --all -- --check
            cargo clippy --all --all-features --tests -- -D warnings
