name: 'Test and run format and lint checks.'
on: # rebuild any PRs and main branch changes
  pull_request:
    branches:
      - main
    paths:
      - '**.rs'
      - 'Cargo.toml'
      - '.devcontainer/**'
  push:
    branches:
      - main
    paths:
      - '**.rs'
      - 'Cargo.toml'
      - '.devcontainer/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write
      pull-requests: write
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and run Dev Container task
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/sequinsbio/sequintools-devcontainer
          cacheFrom: ghcr.io/sequinsbio/sequintools-devcontainer
          push: always
          eventFilterForPush: push
          env: |
            CARGO_TERM_COLOR=always
            CODECOV_TOKEN=${{ secrets.CODECOV_TOKEN }}
            RUN_ID=${{ github.run_id}}
          runCmd: |
            cargo tarpaulan --all-features --out xml
            codecovcli --verbose upload-process -t $CODECOV_TOKEN -n 'job-name'-$RUN_ID -f cobertura.xml
            cargo fmt --all -- --check
            cargo clippy --all --all-features --tests -- -D warnings
