name: Test and lint code without using the devcontainer

on: # rebuild any PRs and main branch changes
  pull_request:
    branches:
      - main
    paths:
      - '**.rs'
      - 'Cargo.toml'
      - '.devcontainer/**'
  push:
    branches:
      - main
    paths:
      - '**.rs'
      - 'Cargo.toml'
      - '.devcontainer/**'

jobs:
  test:
    runs-on: blacksmith-4vcpu-ubuntu-2204

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy, rustfmt

    - name: Rust cache
      uses: swatinem/rust-cache@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake clang

    - name: Install cargo-llvm-cov
      uses: taiki-e/install-action@cargo-llvm-cov

    - name: Run format tests and lints
      run: |
        cargo fmt --all -- --check
        cargo clippy --all --all-features --tests -- -D warnings

    - name: Generate test coverage
      run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info

    - name: Upload coverage to Codecov
      if: github.actor != 'dependabot[bot]'
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: unittest
        name: job-name-${{ github.run_id }}
        verbose: true
        fail_ci_if_error: true
