name: Test and lint code without using the devcontainer

on: # rebuild any PRs and main branch changes
  pull_request:
    branches:
      - main
    paths:
      - '**.rs'
      - 'Cargo.toml'
      - '.devcontainer/**'
  push:
    branches:
      - main
    paths:
      - '**.rs'
      - 'Cargo.toml'
      - '.devcontainer/**'

jobs:
  test:
    runs-on: blacksmith-4vcpu-ubuntu-2204

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy, rustfmt

    - name: Rust cache
      uses: swatinem/rust-cache@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake clang

    - name: Install cargo-tarpaulin
      uses: actions-rs/install@v0.1
      with:
        crate: cargo-tarpaulin
        version: latest

    - name: Run cargo-tarpaulin
      run: cargo tarpaulin --verbose --all-features --out xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: unittest
        name: job-name-${{ github.run_id }}
        verbose: true

    - name: Run format tests and lints
      run: |
        cargo fmt --all -- --check
        cargo clippy --all --all-features --tests -- -D warnings
